# Generated by Django 3.2.2 on 2021-05-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
